---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # flux
  - ../../base/apps/flux-operator.yml
  - ../../base/apps/flux-instance.yml
  - ../../base/apps/flux-web-secret.yml

  # metallb
  - ../../base/apps/metallb.yml

  # ingress-nginx
  - ../../base/apps/ingress-nginx.yml

  # envoy-gateway
  - ../../base/apps/envoy-gateway.yml

  # cert-manager
  - ../../base/apps/cert-manager.yml
  - ../../base/apps/cert-manager-cluster-issurer.yml

  # dex
  - ../../base/apps/dex.yml
  - ../../base/apps/dex-secret.yml
  - ../../base/apps/dex-flux-web-secret.yml

  # route53-dynamic-dns
  - ../../base/apps/route53-dynamic-dns.yml
  - ../../base/apps/route53-dynamic-dns-secret.yml

  # rook-ceph
  - ../../base/apps/rook-ceph-operator.yml
  - ../../base/apps/rook-ceph-cluster.yml
  - ../../base/apps/rook-ceph.yml

  # victoria-metrics
  - ../../base/apps/victoria-metrics-operator.yml
  - ../../base/apps/victoria-metrics.yml

  # node-exporter
  - ../../base/apps/node-exporter.yml

  # fronius-exporter
  - ../../base/apps/fronius-exporter.yml

  # grafana
  - ../../base/apps/grafana-namespace.yml
  - ../../base/apps/grafana-operator.yml
  - ../../base/apps/grafana.yml
  - ../../base/apps/grafana-secret.yml

  # tuppr
  - ../../base/apps/tuppr.yml
  - ../../base/apps/tuppr-config.yml

  # kube-state-metrics
  - ../../base/apps/kube-state-metrics.yml

  # reloader
  - ../../base/apps/reloader.yml

  # # pihole
  # - ../../base/apps/pihole.yml
